server:
  port: 0

spring:
  application:
    name: agent-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nistagramAgent?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Belgrade
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: Agent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    nonSecurePortEnabled: true
    securePortEnabled: false
    securePort: ${server.port}

api:
  userService: http://localhost:8081/user-service/user
  postService: http://localhost:8081/post-service/post
